name: oil1
on: 
  workflow_dispatch:
    #branches:
    #  - main
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean 
  schedule:
    - cron: "32 0 * * *"

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  

      - name: Setup Node.js
        uses: actions/setup-node@v2  
        with:
          node-version: '14'

      - name: npm install
        run: npm install
      
      - name: Start task
        run: node task/oil.js
                    # 提交并推送修改
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else   
            git commit -m "update oil.md"
            git push
          fi