name: weather
on: 
  workflow_dispatch:
    #branches:
    #  - main
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean 
  schedule:
    - cron: "30 1,6 * * *"

jobs:
  start:
    runs-on: ubuntu-latest

    env: 
      EMAIL_NAME: ${{ secrets.EMAIL_NAME }}

    steps:
      - name: Run a one-line script
        run: echo $EMAIL_NAME  # 打印环境变量值以确认其存在和正确性

      - uses: actions/checkout@v4 

      - name: Setup Node.js
        uses: actions/setup-node@v4  
        with:
          node-version: '20'

      - name: npm install
        run: npm install
      
      - name: Start task
        run: node docs/task/weather.js
                    # 提交并推送修改
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else   
            git commit -m "update weather.md"
            git push
          fi